search_input = "//input[@id='wc-block-search__input-1']"
search_btn = "//button[@class='wc-block-product-search__button']"
price_filter_min = "//span[@class='ui-slider-handle ui-corner-all ui-state-default'][1]"
price_filter_max = "//span[@class='ui-slider-handle ui-corner-all ui-state-default'][2]"
price_filter_btn = "//button[text()='Filter']"
slider = "//div[@class='price_slider_wrapper']"
next_page_btn = "//a[@class='next page-numbers']"
all_products_name = "//ul[@class='products columns-4']//h2"
all_products_price = "//ul[@class='products columns-4']//span[@class='price']"
pages_amount = "//a[@class='page-numbers']"
